//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc5RazorAutenticacao.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SampleDatabaseEntities1 : DbContext
    {
        public SampleDatabaseEntities1()
            : base("name=SampleDatabaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cursos> Cursos { get; set; }
        /*Adiciona entidade ou retorna a coleção de entidades do tipo Cursos */

        /*Uma versão não genérica do DbSet <TEntity> que pode ser usada quando o tipo de entidade 
         * não é conhecido no momento da criação.*/
    }
}
